language: c
sudo: false

matrix:
  include:
    - env: TASK="osx"
      os: osx
      compiler: clang
# workaround travis error:
# /Users/travis/build.sh: line 159: shell_session_update: command not found
# https://github.com/bizz84/SwiftyStoreKit/commit/68a67eef94670964e62ea473860b82780c386c77
      before_install:
        - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 || curl -sSL https://rvm.io/mpapis.asc | gpg --import -
        - rvm get stable
    - env: TASK="ios"
      os: osx
      compiler: clang
# workaround travis error:
# /Users/travis/build.sh: line 159: shell_session_update: command not found
# https://github.com/bizz84/SwiftyStoreKit/commit/68a67eef94670964e62ea473860b82780c386c77
      before_install:
        - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 || curl -sSL https://rvm.io/mpapis.asc | gpg --import -
        - rvm get stable
    - env: TASK="coverage" # code coverage
      os: linux
      dist: trusty
      compiler: gcc
      addons: {apt: {packages: [libasound2-dev]}}
      after_success: bash <(curl -s https://codecov.io/bash)
    - env: TASK="shared"   # shared libraries
      os: linux
      dist: trusty
      compiler: gcc
      addons: {apt: {packages: [libasound2-dev]}}
    - env: TASK="gcc6"   # gcc-6
      os: linux
      dist: trusty
      compiler: gcc-6
      addons: {apt: {packages: [libasound2-dev, gcc-6],  sources: [ubuntu-toolchain-r-test]}}
    - env: TASK="arm-linux-gnueabihf-gcc" # arm build
      os: linux
      dist: trusty
      compiler: arm-linux-gnueabihf-gcc
      addons: {apt: {packages: [pkg-config-arm-linux-gnueabihf, libc6-dev-armhf-cross, gcc-arm-linux-gnueabihf, binutils-arm-linux-gnueabihf]}}
    - env: TASK="winbuild" # windows build
      os: linux
      dist: trusty
      compiler: i686-w64-mingw32-gcc
      addons: {apt: {packages: [wine, xvfb, binutils-mingw-w64-i686, mingw-w64-i686-dev, gcc-mingw-w64-i686]}}
      #    - env: TASK="winbuild_shared" # windows build shared libraries
      #os: linux
      #dist: trusty
      #compiler: i686-w64-mingw32-gcc
      #addons: {apt: {packages: [wine, xvfb, binutils-mingw-w64-i686, mingw-w64-i686-dev, gcc-mingw-w64-i686]}}


script:
  - ./run_testsuite.sh "$TASK"


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VQXmVb9lTL4Yo58doWyCkdPTaDoe7sHPnOMCcJMPuxOpK1d/JWkm9Pp2UV8L/32JkCOO32azPJ1R1nr7uz6GFs0CwNAW+FO24mRex/h3CaH33eu7fQkq4MwfBqa19qqPoUX7KB8iofT6KyRxNrC8Z+zYPR9gogP2VrLSldi0Wva3+On/9tnj+e0/Cy2lTfjyXGvdFoDCM+WtbVz38IZrrAl7TG9azCorM0AaHr1U57DNVKQNlWdTJLiN2tzc5971nA7/Ws+ZoNK2ZWV6fIghgLju/h25JIqKpXB/Wi5QyUWY0pZ5oAEfqIgJchZ3e5qLS4bARsJwXTL8BFfwStA05qBTKI5M0lj93u1/d4tuVJzSP5LTJJelFYPsLVtyOKglFHr/Pb4PhieHJXjr/jig8P48nP+jgXcQjpP4uLZ3D1Z01///QCWCiHXloSurQkA0fhQSyeCHGNiTPEjAYfcFAjlH5/C1tsRLIerxm8hdGDhF0x7lg9j069B0Yet5GINiBeBZdTph1r6YWYQUqAwb8gAYt20KE/i/f5TSIFOd9jDOrPHLgSZX0N+C7x6PqVTxBGMksNJtf+PNOrBC5+VbYxdw0ldX1AveBD4oW9bcJ9wo3rAsFGZ8q6Vnl0r3U48eKWtMUf4//aq4Ab1h/LP8t+c+XyEXfMNh4WpJ4lySn4s="

addons:
  coverity_scan:
    project:
      name: "MycroftAI/mimic"
      description: "TTS for Mycroft AI"
    notification_email: sergioller@gmail.com
    # build_command_prepend: "<Your build preprocessing command here>"
    build_command: ./run_testsuite.sh
    branch_pattern: coverity_scan

